const COMPANY_VERIFICATION = {
    PENDING: 'Pending',
    VERIFIED: 'Verified',
    SUSPENDED: 'Suspended'
};
const COMPANY_VERIFICATION_MAP = COMPANY_VERIFICATION;

module.exports = { COMPANY_VERIFICATION, COMPANY_VERIFICATION_MAP };
